version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    volumes:
      - data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
  agency-manager-server:
    build:
      context: ./agencies-manager
      dockerfile: ./Dockerfile
    container_name: agency_manager-server
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - mongodb

  agency-manager-ui:
    build:
      context: ./agency-manager-front
      dockerfile: ./Dockerfile
    container_name: agency_manager-ui
    ports:
      - 8888:80

volumes:
  data: { }
networks:
  default:
    name: mongodb_network